# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170818_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Item',
        ),
    ]
