# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170818_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='desc',
        ),
    ]
